DROP TABLE IF EXISTS DOMAIN;
DROP TABLE IF EXISTS LINK;
DROP TABLE IF EXISTS WORD;
DROP TABLE IF EXISTS INLIST;
DROP TABLE IF EXISTS REFERENCE;

CREATE TABLE DOMAIN
(
	ID INT	PRIMARY KEY UNIQUE,
	DOMAIN TEXT
);

CREATE TABLE LINK
(
	ID INT PRIMARY KEY UNIQUE,
	DOMAIN INT,
	LINK TEXT,
	FOREIGN KEY(DOMAIN) REFERENCES DOMAIN(ID)
);

CREATE TABLE REFERENCE
(
	SRC INT,
	REF INT,
	PRIMARY KEY(SRC, REF)
	FOREIGN KEY(SRC) REFERENCES LINK(ID),
	FOREIGN KEY(REF) REFERENCES LINK(ID)
);

CREATE TABLE INLIST
(
	WORD INT,
	LINK INT,
	PRIMARY KEY(WORD, LINK),
	FOREIGN KEY(WORD) REFERENCES WORD(ID),
	FOREIGN KEY(LINK) REFERENCES LINK(ID)
);

CREATE TABLE WORD
(
	ID INT,
	WORD TEXT,
	PRIMARY KEY(ID)
);