SELECT D1.DOMAIN, L1.LINK, D2.DOMAIN, L2.LINK FROM REFERENCE
JOIN 
	(SELECT * FROM LINK JOIN DOMAIN ON LINK.DOMAIN = DOMAIN.ID)AS L1
	ON REFERENCE.SRC = L1.ID
JOIN 
	(SELECT * FROM LINK JOIN DOMAIN ON LINK.DOMAIN = DOMAIN.ID) AS L2
	ON REFERENCE.REF = L2.ID
JOIN
	(SELECT * FROM DOMAIN WHERE DOMAIN.ID = 0) AS D1
	ON L1.DOMAIN = D1.ID
JOIN 
	(SELECT * FROM DOMAIN WHERE DOMAIN.ID = 2) AS D2
	ON L2.DOMAIN = D2.ID;